name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: customer-purchase-app
  DOCKER_IMAGE: customer-purchase-app

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:latest .
          docker build -t ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:${{github.sha}} .

      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:latest
          docker push ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:${{github.sha}}

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          images: ${{ secrets.DOCKER_USERNAME }}/${{env.DOCKER_IMAGE}}:latest
        
